USE QLBHONLINE;
GO

-- Dữ liệu bảng discount

INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Deal sốc', N'Áp dụng cho tất cả sản phẩm', 19);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Flash Sale', N'Chỉ áp dụng cho thành viên', 40);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Khuyến mãi cuối năm', N'Áp dụng cho tất cả sản phẩm', 40);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Flash Sale', N'Áp dụng cho tất cả sản phẩm', 41);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Deal sốc', N'Chỉ áp dụng cho thành viên', 9);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Deal sốc', N'Chỉ áp dụng cho thành viên', 41);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Deal sốc', N'Chỉ áp dụng cho thành viên', 20);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Ưu đãi mùa hè', N'Áp dụng cho tất cả sản phẩm', 7);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Ưu đãi mùa hè', N'Chỉ áp dụng cho thành viên', 43);
INSERT INTO discount (dis_name, disc_desc, discount_percent) VALUES (N'Flash Sale', N'Chỉ áp dụng cho thành viên', 13);

-- Dữ liệu bảng users (10 admin)

INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user1', N'pass1', N'Cần Thơ', N'0932294079', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user2', N'pass2', N'Nghệ An', N'0997472725', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user3', N'pass3', N'Đà Nẵng', N'0950318193', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user4', N'pass4', N'Nghệ An', N'0968710613', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user5', N'pass5', N'TP. Hồ Chí Minh', N'0982819965', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user6', N'pass6', N'Hà Nội', N'0970104170', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user7', N'pass7', N'Hà Nội', N'0971254868', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user8', N'pass8', N'Hải Phòng', N'0969155411', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user9', N'pass9', N'Hà Nội', N'0924498222', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user10', N'pass10', N'Hà Nội', N'0973255562', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user11', N'pass11', N'Cần Thơ', N'0927955664', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user12', N'pass12', N'Nghệ An', N'0962695315', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user13', N'pass13', N'Đà Nẵng', N'0987071532', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user14', N'pass14', N'Nghệ An', N'0999864631', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user15', N'pass15', N'Đà Nẵng', N'0997588523', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user16', N'pass16', N'Hà Nội', N'0916652377', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user17', N'pass17', N'Cần Thơ', N'0928837019', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user18', N'pass18', N'Nghệ An', N'0970966303', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user19', N'pass19', N'Huế', N'0912699865', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user20', N'pass20', N'Hà Nội', N'0982334417', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user21', N'pass21', N'Hải Phòng', N'0918212221', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user22', N'pass22', N'Hải Phòng', N'0932316384', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user23', N'pass23', N'Nghệ An', N'0934943430', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user24', N'pass24', N'Đà Nẵng', N'0978346011', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user25', N'pass25', N'Nghệ An', N'0940197798', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user26', N'pass26', N'TP. Hồ Chí Minh', N'0955989107', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user27', N'pass27', N'TP. Hồ Chí Minh', N'0953107696', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user28', N'pass28', N'Nam Định', N'0935599526', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user29', N'pass29', N'Huế', N'0986815366', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user30', N'pass30', N'Nghệ An', N'0993964001', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user31', N'pass31', N'Đà Nẵng', N'0945518067', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user32', N'pass32', N'Nam Định', N'0937830789', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user33', N'pass33', N'Nghệ An', N'0980031241', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user34', N'pass34', N'Nghệ An', N'0983207643', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user35', N'pass35', N'Cần Thơ', N'0932079925', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user36', N'pass36', N'Hà Nội', N'0926198012', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user37', N'pass37', N'Đà Nẵng', N'0943869481', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user38', N'pass38', N'Hải Phòng', N'0971083455', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user39', N'pass39', N'Nghệ An', N'0945987738', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user40', N'pass40', N'TP. Hồ Chí Minh', N'0991541277', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user41', N'pass41', N'Hải Phòng', N'0982638108', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user42', N'pass42', N'Nam Định', N'0949084367', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user43', N'pass43', N'Hà Nội', N'0979048802', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user44', N'pass44', N'Đà Nẵng', N'0920394449', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user45', N'pass45', N'Hải Phòng', N'0971706083', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user46', N'pass46', N'Nghệ An', N'0964670819', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user47', N'pass47', N'Cần Thơ', N'0923781803', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user48', N'pass48', N'Đà Nẵng', N'0967876292', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user49', N'pass49', N'Nam Định', N'0929637571', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user50', N'pass50', N'Nam Định', N'0964098043', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user51', N'pass51', N'Đà Nẵng', N'0913153389', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user52', N'pass52', N'Hải Phòng', N'0980280855', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user53', N'pass53', N'Hải Phòng', N'0952593857', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user54', N'pass54', N'Nghệ An', N'0960272833', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user55', N'pass55', N'Hải Phòng', N'0964577972', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user56', N'pass56', N'Hà Nội', N'0943538114', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user57', N'pass57', N'Nam Định', N'0930612321', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user58', N'pass58', N'Hải Phòng', N'0970029919', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user59', N'pass59', N'Huế', N'0987470145', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user60', N'pass60', N'Cần Thơ', N'0965864559', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user61', N'pass61', N'TP. Hồ Chí Minh', N'0917187280', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user62', N'pass62', N'Hà Nội', N'0942247679', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user63', N'pass63', N'Nghệ An', N'0981153454', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user64', N'pass64', N'Hà Nội', N'0918032737', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user65', N'pass65', N'Nam Định', N'0968913777', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user66', N'pass66', N'Nam Định', N'0972799981', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user67', N'pass67', N'Nam Định', N'0943101849', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user68', N'pass68', N'Hải Phòng', N'0988205107', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user69', N'pass69', N'Cần Thơ', N'0975909455', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user70', N'pass70', N'Nam Định', N'0989210820', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user71', N'pass71', N'Đà Nẵng', N'0991486769', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user72', N'pass72', N'Hà Nội', N'0916367877', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user73', N'pass73', N'TP. Hồ Chí Minh', N'0971182998', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user74', N'pass74', N'Đà Nẵng', N'0916487928', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user75', N'pass75', N'TP. Hồ Chí Minh', N'0991401545', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user76', N'pass76', N'Hải Phòng', N'0939821138', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user77', N'pass77', N'Nam Định', N'0976759112', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user78', N'pass78', N'Đà Nẵng', N'0975328610', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user79', N'pass79', N'Cần Thơ', N'0931513313', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user80', N'pass80', N'Hải Phòng', N'0937565649', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user81', N'pass81', N'TP. Hồ Chí Minh', N'0954292075', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user82', N'pass82', N'Cần Thơ', N'0942844272', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user83', N'pass83', N'Cần Thơ', N'0982034043', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user84', N'pass84', N'Huế', N'0917281788', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user85', N'pass85', N'Huế', N'0947937187', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user86', N'pass86', N'Hà Nội', N'0986230275', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user87', N'pass87', N'TP. Hồ Chí Minh', N'0977888555', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user88', N'pass88', N'Huế', N'0920734633', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user89', N'pass89', N'Huế', N'0949575695', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user90', N'pass90', N'Huế', N'0962201987', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user91', N'pass91', N'Đà Nẵng', N'0933999012', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user92', N'pass92', N'Hải Phòng', N'0970393531', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user93', N'pass93', N'Nam Định', N'0968786056', N'admin');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user94', N'pass94', N'Huế', N'0943089418', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user95', N'pass95', N'Đà Nẵng', N'0981208086', N'user');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user96', N'pass96', N'Đà Nẵng', N'0938803979', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user97', N'pass97', N'Nam Định', N'0948633320', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user98', N'pass98', N'Đà Nẵng', N'0950147433', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user99', N'pass99', N'Hải Phòng', N'0993590219', N'staff');
INSERT INTO users (username, passwords, user_address, telephone, role) VALUES (N'user100', N'pass100', N'Hà Nội', N'0962874164', N'user');
-- Dữ liệu bảng product

INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Kính Mát 0', N'Hàng nhập khẩu', N'Giày dép', 1763824, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Đồng Hồ 1', N'Sản phẩm bán chạy', N'Phụ kiện', 1566754, 3);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Giày Sneaker 2', N'Kiểu dáng thời trang', N'Thời trang nữ', 306307, 10);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 3', N'Hàng nhập khẩu', N'Thời trang nữ', 1315220, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Giày Sneaker 4', N'Sản phẩm bán chạy', N'Phụ kiện', 556461, 7);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Kính Mát 5', N'Kiểu dáng thời trang', N'Phụ kiện', 289299, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Túi Xách 6', N'Kiểu dáng thời trang', N'Thời trang nữ', 1583634, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Đồng Hồ 7', N'Sản phẩm bán chạy', N'Thời trang nữ', 467697, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Giày Sneaker 8', N'Kiểu dáng thời trang', N'Phụ kiện', 1986571, 4);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Quần Jean 9', N'Kiểu dáng thời trang', N'Giày dép', 427543, 10);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Túi Xách 10', N'Hàng nhập khẩu', N'Thời trang nữ', 903710, 3);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 11', N'Sản phẩm bán chạy', N'Giày dép', 1697795, 9);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Túi Xách 12', N'Sản phẩm bán chạy', N'Giày dép', 1488467, 10);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Quần Jean 13', N'Chất liệu cao cấp', N'Phụ kiện', 1753006, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 14', N'Hàng nhập khẩu', N'Thời trang nữ', 505886, 10);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Đồng Hồ 15', N'Kiểu dáng thời trang', N'Giày dép', 1874988, 6);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Túi Xách 16', N'Kiểu dáng thời trang', N'Giày dép', 1817266, 7);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Váy Đầm 17', N'Kiểu dáng thời trang', N'Thời trang nam', 656402, 10);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Giày Sneaker 18', N'Sản phẩm bán chạy', N'Phụ kiện', 1868775, 6);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Váy Đầm 19', N'Chất liệu cao cấp', N'Thời trang nam', 507030, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Giày Sneaker 20', N'Chất liệu cao cấp', N'Giày dép', 251157, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Váy Đầm 21', N'Chất liệu cao cấp', N'Thời trang nữ', 1837596, 8);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Giày Sneaker 22', N'Hàng nhập khẩu', N'Giày dép', 518265, 3);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Váy Đầm 23', N'Chất liệu cao cấp', N'Thời trang nữ', 1012809, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 24', N'Chất liệu cao cấp', N'Giày dép', 1536530, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Quần Jean 25', N'Chất liệu cao cấp', N'Giày dép', 1869683, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Váy Đầm 26', N'Mẫu mới 2024', N'Thời trang nữ', 169397, 7);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Váy Đầm 27', N'Sản phẩm bán chạy', N'Thời trang nữ', 1626070, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Quần Jean 28', N'Mẫu mới 2024', N'Giày dép', 925277, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Túi Xách 29', N'Sản phẩm bán chạy', N'Giày dép', 1858376, 7);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Kính Mát 30', N'Mẫu mới 2024', N'Thời trang nữ', 1343008, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Túi Xách 31', N'Mẫu mới 2024', N'Thời trang nữ', 688004, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Giày Sneaker 32', N'Chất liệu cao cấp', N'Phụ kiện', 1286254, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Kính Mát 33', N'Hàng nhập khẩu', N'Giày dép', 1750381, 9);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Kính Mát 34', N'Kiểu dáng thời trang', N'Phụ kiện', 392999, 3);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Áo Thun 35', N'Kiểu dáng thời trang', N'Thời trang nam', 1501334, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 36', N'Hàng nhập khẩu', N'Thời trang nữ', 1829241, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Quần Jean 37', N'Hàng nhập khẩu', N'Phụ kiện', 1726541, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 38', N'Chất liệu cao cấp', N'Giày dép', 392504, 10);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 39', N'Mẫu mới 2024', N'Thời trang nam', 986333, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 40', N'Chất liệu cao cấp', N'Giày dép', 279975, 6);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 41', N'Sản phẩm bán chạy', N'Phụ kiện', 599783, 6);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Đồng Hồ 42', N'Kiểu dáng thời trang', N'Phụ kiện', 1613456, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Áo Thun 43', N'Sản phẩm bán chạy', N'Phụ kiện', 1638155, 7);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Túi Xách 44', N'Hàng nhập khẩu', N'Thời trang nam', 604530, 7);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Quần Jean 45', N'Hàng nhập khẩu', N'Phụ kiện', 1321257, 1);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Áo Thun 46', N'Sản phẩm bán chạy', N'Thời trang nam', 189141, 3);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Áo Thun 47', N'Kiểu dáng thời trang', N'Giày dép', 1630795, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Đồng Hồ 48', N'Sản phẩm bán chạy', N'Phụ kiện', 1449002, NULL);
INSERT INTO product (product_name, pro_desc, category, price, discount_id) VALUES (N'Mũ Lưỡi Trai 49', N'Hàng nhập khẩu', N'Thời trang nữ', 1299650, NULL);

-- Dữ liệu bảng shopping_session

INSERT INTO shopping_session (users_id, total) VALUES (79, 644023);
INSERT INTO shopping_session (users_id, total) VALUES (86, 528264);
INSERT INTO shopping_session (users_id, total) VALUES (7, 864993);
INSERT INTO shopping_session (users_id, total) VALUES (87, 1508322);
INSERT INTO shopping_session (users_id, total) VALUES (50, 461412);
INSERT INTO shopping_session (users_id, total) VALUES (13, 1552801);
INSERT INTO shopping_session (users_id, total) VALUES (85, 1642372);
INSERT INTO shopping_session (users_id, total) VALUES (46, 177337);
INSERT INTO shopping_session (users_id, total) VALUES (86, 247526);
INSERT INTO shopping_session (users_id, total) VALUES (3, 845738);
INSERT INTO shopping_session (users_id, total) VALUES (13, 533521);
INSERT INTO shopping_session (users_id, total) VALUES (25, 120612);
INSERT INTO shopping_session (users_id, total) VALUES (3, 510042);
INSERT INTO shopping_session (users_id, total) VALUES (61, 1751867);
INSERT INTO shopping_session (users_id, total) VALUES (61, 1917504);
INSERT INTO shopping_session (users_id, total) VALUES (41, 1013898);
INSERT INTO shopping_session (users_id, total) VALUES (28, 183460);
INSERT INTO shopping_session (users_id, total) VALUES (77, 1956984);
INSERT INTO shopping_session (users_id, total) VALUES (5, 804257);
INSERT INTO shopping_session (users_id, total) VALUES (31, 1937878);
INSERT INTO shopping_session (users_id, total) VALUES (46, 1486458);
INSERT INTO shopping_session (users_id, total) VALUES (18, 1137940);
INSERT INTO shopping_session (users_id, total) VALUES (15, 425557);
INSERT INTO shopping_session (users_id, total) VALUES (37, 808002);
INSERT INTO shopping_session (users_id, total) VALUES (57, 1296205);
INSERT INTO shopping_session (users_id, total) VALUES (69, 480076);
INSERT INTO shopping_session (users_id, total) VALUES (54, 1921439);
INSERT INTO shopping_session (users_id, total) VALUES (26, 1876325);
INSERT INTO shopping_session (users_id, total) VALUES (29, 1887346);
INSERT INTO shopping_session (users_id, total) VALUES (45, 503206);
INSERT INTO shopping_session (users_id, total) VALUES (26, 1760321);
INSERT INTO shopping_session (users_id, total) VALUES (82, 1664759);
INSERT INTO shopping_session (users_id, total) VALUES (55, 1760012);
INSERT INTO shopping_session (users_id, total) VALUES (3, 880476);
INSERT INTO shopping_session (users_id, total) VALUES (42, 682000);
INSERT INTO shopping_session (users_id, total) VALUES (52, 1674352);
INSERT INTO shopping_session (users_id, total) VALUES (5, 421150);
INSERT INTO shopping_session (users_id, total) VALUES (39, 513959);
INSERT INTO shopping_session (users_id, total) VALUES (53, 974370);
INSERT INTO shopping_session (users_id, total) VALUES (80, 1529782);
INSERT INTO shopping_session (users_id, total) VALUES (93, 1507258);
INSERT INTO shopping_session (users_id, total) VALUES (52, 567572);
INSERT INTO shopping_session (users_id, total) VALUES (90, 1864987);
INSERT INTO shopping_session (users_id, total) VALUES (26, 1783165);
INSERT INTO shopping_session (users_id, total) VALUES (17, 561784);
INSERT INTO shopping_session (users_id, total) VALUES (46, 548469);
INSERT INTO shopping_session (users_id, total) VALUES (6, 458647);
INSERT INTO shopping_session (users_id, total) VALUES (68, 1038848);
INSERT INTO shopping_session (users_id, total) VALUES (67, 127201);
INSERT INTO shopping_session (users_id, total) VALUES (11, 1754463);
INSERT INTO shopping_session (users_id, total) VALUES (22, 366228);
INSERT INTO shopping_session (users_id, total) VALUES (15, 111969);
INSERT INTO shopping_session (users_id, total) VALUES (77, 847915);
INSERT INTO shopping_session (users_id, total) VALUES (27, 984515);
INSERT INTO shopping_session (users_id, total) VALUES (20, 405183);
INSERT INTO shopping_session (users_id, total) VALUES (98, 1077666);
INSERT INTO shopping_session (users_id, total) VALUES (76, 900292);
INSERT INTO shopping_session (users_id, total) VALUES (75, 982959);
INSERT INTO shopping_session (users_id, total) VALUES (27, 465759);
INSERT INTO shopping_session (users_id, total) VALUES (68, 1985695);
INSERT INTO shopping_session (users_id, total) VALUES (69, 608262);
INSERT INTO shopping_session (users_id, total) VALUES (9, 745654);
INSERT INTO shopping_session (users_id, total) VALUES (24, 1213894);
INSERT INTO shopping_session (users_id, total) VALUES (3, 1088924);
INSERT INTO shopping_session (users_id, total) VALUES (5, 701871);
INSERT INTO shopping_session (users_id, total) VALUES (100, 418154);
INSERT INTO shopping_session (users_id, total) VALUES (60, 1401793);
INSERT INTO shopping_session (users_id, total) VALUES (4, 132709);
INSERT INTO shopping_session (users_id, total) VALUES (41, 1871437);
INSERT INTO shopping_session (users_id, total) VALUES (57, 950468);
INSERT INTO shopping_session (users_id, total) VALUES (58, 461844);
INSERT INTO shopping_session (users_id, total) VALUES (70, 1950080);
INSERT INTO shopping_session (users_id, total) VALUES (77, 1255918);
INSERT INTO shopping_session (users_id, total) VALUES (90, 1260051);
INSERT INTO shopping_session (users_id, total) VALUES (99, 815160);
INSERT INTO shopping_session (users_id, total) VALUES (71, 835405);
INSERT INTO shopping_session (users_id, total) VALUES (64, 1958890);
INSERT INTO shopping_session (users_id, total) VALUES (37, 1808400);
INSERT INTO shopping_session (users_id, total) VALUES (58, 375507);
INSERT INTO shopping_session (users_id, total) VALUES (49, 1366234);

-- Dữ liệu bảng cart_item

INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (21, 2, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (50, 40, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (34, 41, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (31, 46, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (22, 3, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (55, 6, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (76, 29, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (13, 19, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (72, 45, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (78, 27, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (64, 26, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (46, 19, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (61, 31, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (31, 36, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (73, 5, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (21, 5, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (15, 8, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (31, 8, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (64, 36, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (13, 18, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (12, 11, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (37, 11, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (13, 37, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (77, 41, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (10, 48, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (7, 42, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (21, 18, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (36, 40, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (54, 38, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (24, 36, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (78, 12, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (8, 41, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (16, 24, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (38, 14, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (54, 25, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (58, 15, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (19, 14, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (52, 46, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (37, 39, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (55, 19, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (12, 19, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (13, 29, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (72, 11, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (33, 11, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (45, 2, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (16, 47, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (25, 27, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (34, 38, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (43, 34, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (79, 19, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (76, 45, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (68, 48, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (27, 46, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (55, 10, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (21, 16, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (32, 1, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (18, 46, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (52, 11, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (26, 22, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (31, 6, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (59, 44, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (80, 24, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (56, 28, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (6, 5, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (15, 34, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (76, 21, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (9, 18, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (43, 16, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (15, 50, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (15, 45, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (3, 13, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (12, 31, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (37, 21, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (30, 22, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (30, 21, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (41, 23, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (67, 5, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (11, 31, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (41, 20, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (12, 35, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (32, 31, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (50, 27, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (55, 47, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (28, 48, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (48, 14, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (2, 16, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (57, 5, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (45, 43, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (74, 33, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (70, 23, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (53, 43, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (35, 45, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (17, 47, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (67, 22, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (14, 33, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (5, 42, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (21, 42, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (18, 26, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (35, 33, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (75, 4, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (32, 10, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (66, 13, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (37, 8, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (72, 42, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (60, 33, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (59, 30, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (49, 16, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (75, 16, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (77, 47, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (39, 48, 5);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (56, 36, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (11, 7, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (41, 37, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (75, 22, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (65, 26, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (61, 24, 1);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (57, 17, 2);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (49, 39, 4);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (28, 20, 3);
INSERT INTO cart_item (sessions_id, product_id, quantity) VALUES (36, 22, 4);

-- Dữ liệu bảng order_details

INSERT INTO order_details (users_id, total, order_status) VALUES (75, 281889, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (32, 240692, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (6, 272785, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (52, 155509, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (47, 489865, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (34, 1096488, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (4, 1359103, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (17, 1334632, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (10, 1578414, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (62, 1728591, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (84, 689549, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (37, 940458, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (80, 150571, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (87, 1235211, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (4, 1672416, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (16, 786866, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (4, 1276538, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (91, 662162, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (61, 512374, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (67, 1767983, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (24, 290856, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (56, 1969965, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (74, 1351774, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (75, 951891, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (52, 396777, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (67, 1273927, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (26, 749335, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (13, 1263109, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (28, 1325258, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (14, 1442792, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (70, 828115, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (73, 925607, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (87, 651629, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (76, 1349390, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (38, 224238, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (57, 345128, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (74, 892002, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (59, 917889, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (24, 1700605, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (8, 604566, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (24, 517499, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (92, 1746803, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (31, 1044169, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (60, 1183959, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (77, 1553823, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (12, 1940554, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (77, 469959, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (73, 1383288, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (78, 988084, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (69, 925576, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (98, 1252608, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (7, 944653, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (31, 1185193, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (51, 1091086, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (91, 551298, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (44, 777325, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (60, 1725219, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (77, 384679, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (7, 133565, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (47, 1331527, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (72, 855259, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (19, 1058445, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (89, 110497, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (80, 724923, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (25, 259138, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (88, 1280782, N'Đã hủy');
INSERT INTO order_details (users_id, total, order_status) VALUES (57, 891738, N'Đang xử lý');
INSERT INTO order_details (users_id, total, order_status) VALUES (32, 810877, N'Đã giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (98, 1907829, N'Chờ giao');
INSERT INTO order_details (users_id, total, order_status) VALUES (83, 583664, N'Đang xử lý');

-- Dữ liệu bảng order_items

INSERT INTO order_items (order_id, product_id, quantity) VALUES (47, 32, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (58, 13, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (47, 14, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (70, 26, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (61, 29, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (26, 23, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (69, 1, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (12, 48, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (28, 17, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (19, 47, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (4, 38, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (17, 3, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (5, 49, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (12, 2, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (37, 46, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (36, 44, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (52, 42, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (3, 7, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (53, 50, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (49, 39, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (21, 27, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (5, 24, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (37, 47, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (6, 29, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (24, 21, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (11, 39, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (40, 38, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (11, 19, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (32, 35, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (66, 2, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (9, 10, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (35, 16, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (63, 44, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (50, 1, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (54, 36, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (45, 30, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (40, 22, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (31, 12, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (50, 24, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (68, 8, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (2, 39, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (70, 31, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (6, 12, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (42, 28, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (42, 10, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (38, 31, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (69, 19, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (33, 31, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (14, 42, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (27, 47, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (70, 39, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (21, 31, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (46, 23, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (35, 19, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (47, 47, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (18, 23, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (8, 35, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (64, 26, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (61, 2, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (59, 19, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (42, 2, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (53, 3, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (32, 26, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (50, 20, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (15, 15, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (10, 15, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (25, 24, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (23, 27, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (24, 15, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (5, 15, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (55, 3, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (49, 42, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (54, 14, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (41, 46, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (45, 15, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (23, 25, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (12, 8, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (70, 13, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (13, 31, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (12, 23, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (53, 15, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (49, 34, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (25, 5, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (44, 28, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (40, 11, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (69, 21, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (20, 26, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (46, 28, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (44, 38, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (16, 43, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (66, 41, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (43, 48, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (43, 22, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (52, 22, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (41, 22, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (37, 16, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (25, 11, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (39, 26, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (56, 10, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (42, 21, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (65, 21, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (56, 46, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (18, 22, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (48, 16, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (53, 32, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (16, 47, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (30, 37, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (61, 23, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (35, 46, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (27, 4, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (16, 47, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (59, 50, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (25, 14, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (6, 34, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (11, 50, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (60, 31, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (22, 3, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (35, 7, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (18, 39, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (6, 22, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (24, 26, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (52, 25, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (14, 25, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (26, 43, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (28, 31, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (20, 8, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (52, 18, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (70, 13, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (30, 23, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (13, 2, 1);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (38, 28, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (9, 47, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (4, 26, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (52, 43, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (65, 8, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (58, 15, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (10, 44, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (54, 5, 5);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (5, 15, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (58, 7, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (35, 34, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (41, 44, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (7, 42, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (15, 39, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (39, 40, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (69, 42, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (45, 14, 3);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (4, 33, 2);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (57, 13, 4);
INSERT INTO order_items (order_id, product_id, quantity) VALUES (13, 14, 4);